name: Update Workflow Info

on:
  workflow_dispatch:

  schedule:
    - cron: '5 4 * * *' # every day at 4:05 UTC
jobs:
  render:
    name: Render Rmd report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
      - uses: r-lib/actions/setup-renv@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Generate report
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rmarkdown::render("README.Rmd", output_file = "README.md", output_format = "md_document")
          rmarkdown::render("RHub.Rmd", output_file = "RHub.md", output_format = "md_document")

      - name: Set credentials for github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Automatic update" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@9870d48124da805820c70ebc6ba563c715551019
        with:
          directory: ./
          repository:  averissimo/verdepcheck-status
          github_token: ${{ secrets.GITHUB_TOKEN }}
